# np.insert(arr, obj, values, axis)
>`arr` : Input array to be inserted  
>`obj`: The index before which the insertion is to be made  
>`values`: The array of values to be inserted  
>`axis`: The axis along insert in given array, if not given, arr is flattened


In [1]:
import numpy as np

In [2]:
test_insert = np.random.randint(1,3,(2,3,4))
test_insert

array([[[2, 1, 1, 1],
        [1, 1, 1, 2],
        [2, 2, 1, 2]],

       [[2, 1, 2, 1],
        [2, 1, 1, 1],
        [2, 1, 2, 2]]])

In [3]:
np.insert(test_insert,0,[0,0,0,0],axis=0)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[2, 2, 1, 1],
        [1, 1, 2, 1],
        [2, 2, 2, 2]],

       [[2, 2, 1, 2],
        [2, 1, 2, 2],
        [1, 2, 1, 2]]])

In [5]:
np.insert(test_insert, 1,[3,3,4,4],axis=0)



array([[[2, 2, 1, 1],
        [1, 1, 2, 1],
        [2, 2, 2, 2]],

       [[3, 3, 4, 4],
        [3, 3, 4, 4],
        [3, 3, 4, 4]],

       [[2, 2, 1, 2],
        [2, 1, 2, 2],
        [1, 2, 1, 2]]])

In [3]:
test_insert

array([[[2, 1, 1, 1],
        [1, 1, 1, 2],
        [2, 2, 1, 2]],

       [[2, 1, 2, 1],
        [2, 1, 1, 1],
        [2, 1, 2, 2]]])

In [10]:
np.insert(test_insert, 1, [11,22,33,44], axis=1)

array([[[ 2,  1,  1,  1],
        [11, 22, 33, 44],
        [ 1,  1,  1,  2],
        [ 2,  2,  1,  2]],

       [[ 2,  1,  2,  1],
        [11, 22, 33, 44],
        [ 2,  1,  1,  1],
        [ 2,  1,  2,  2]]])