# np.where(condition, operation, ndarray)

In [1]:
import numpy as np

In [2]:
test_ndarray = np.random.randint(1,10,(5))
test_ndarray

array([9, 1, 3, 4, 6])

In [3]:
np.where(test_ndarray>4, 10*test_ndarray, test_ndarray)

array([90,  1,  3,  4, 60])

In [4]:
a = np.array([1, 2, 3])
condition = a==3
operation = a*10
ndarry= a
b = np.where(condition, operation, ndarry)
b

array([ 1,  2, 30])