In [1]:
#show current time
import datetime
current_time = datetime.datetime.now()
print(current_time)
print(current_time.hour)
print(current_time.minute)
print(current_time.second)

2021-10-24 13:47:39.235955
13
47
39


In [9]:
A=1
A

1

In [6]:
for i in range(10):
    a=2
    b=4

In [7]:
a

2

In [5]:
# np.resize
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[8,9,7]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 7]])

In [6]:
np.resize(arr,(2,6))


array([[1, 2, 3, 4, 5, 6],
       [8, 9, 7, 1, 2, 3]])

In [7]:
# initiate a numpy array with all ones
np.ones((3,2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [2]:
sdf
b = [4,5,6]
b = [4,5,6]
b = [4,5,6]
b = [4,5,6]
b = [4,5,6]
b = [4,5,6]
b = [4,5,6]
b = [4,5,6]
b = [4,5,6] b = [4,5,6] f

In [3]:
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]
 = [4,5,6]


((1, 2, 3), (4, 5, 6))