In [7]:
import numpy as np

In [2]:
import imp
imp.find_module("snipket")

(<_io.TextIOWrapper name='C:\\Users\\Admin\\PycharmProjects\\snipket.py' mode='r' encoding='utf-8'>,
 'C:\\Users\\Admin\\PycharmProjects\\snipket.py',
 ('.py', 'r', 1))

In [5]:
class p():
    total = 0
    def __init__(self,name):
        self.name = name
        nonlocal total
total += jk1

SyntaxError: no binding for nonlocal 'total' found (<ipython-input-5-8424215fd3b5>, line 5)

In [6]:
sanket = p("sank")
sanket = p("dank")

UnboundLocalError: local variable 'total' referenced before assignment

In [9]:
a = np.array([[1,2,1], [3, 4, 3]])
np.unique(a, return_index= True, return_counts=True)

(array([1, 2, 3, 4]),
 array([0, 1, 3, 4], dtype=int64),
 array([2, 1, 2, 1], dtype=int64))

In [10]:
a = np.array([[1,2,1], [3, 4, 3]])
np.delete(a,0,axis = 1)

array([[2, 1],
       [4, 3]])

In [1]:
numpy.ndarray.__dict__
# numpy.ndarray.__name__

NameError: name 'numpy' is not defined

In [2]:
"5" == 5

False