In [6]:
import numpy as np

In [7]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Rotate array to right by n positions

In [9]:
np.roll(array,1)

array([9, 0, 1, 2, 3, 4, 5, 6, 7, 8])

## Rotate array to left by n posiditons

In [17]:
array = np.roll(array, -1)
array

array([6, 7, 8, 9, 0, 1, 2, 3, 4, 5])