# Create a Numpy Array:
> A numpy array is similar to list except it has only one type mostly integer or float i.e it must be homogeneous </br>
> It is fixed size

In [1]:
a = [1,2,3,4]
import numpy as np

In [2]:
array = np.array(a)
array

array([1, 2, 3, 4])

In [3]:
type(array)  # type

numpy.ndarray

In [6]:
array.dtype  # data type

dtype('int32')

In [7]:
array.size  # size

4

In [8]:
array.ndim  # represents array dimensions or rank of array

1

In [9]:
array.shape  # Indicates shape of array in each dimension

(4,)

In [12]:
b = [1.1, 123.3, 1323.43, 33.44, 343.44]
array2 = np.array(b)
array2

array([1.10000e+00, 1.23300e+02, 1.32343e+03, 3.34400e+01, 3.43440e+02])

In [14]:
array2.dtype


dtype('float64')

In [16]:
array2[0]=10.0  # Assigne index 0 to 10.0
array2

array([  10.  ,  123.3 , 1323.43,   33.44,  343.44])

In [18]:
c = array2[2:5]
c

array([1323.43,   33.44,  343.44])